#日志配置mybatis-spring-boot-starter
logging:
  file: d:/temp/spring-boot.log
  level:
    root: info

#数据源
spring:
  datasource:
    #useUnicode=true&characterEncoding=utf-8解决sql执行时中文乱码
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #always initialize the DataSource regardless of its type
    initialization-mode: always
    #不设置的情况下，默认从root classpath locations加载：schema.sql and data.sql
    schema: classpath:init-sql/schema-mysql.sql
#    data: classpath:init-sql/data-mysql.sql
#    sql-script-encoding: utf-8
  redis:
    host: 127.0.0.1
    port: 6379
#    password:

#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:/mapper/*/*.xml
#  type-aliases-package: com.anonym.wxminiprogram.dao

#redis