CREATE TABLE IF NOT EXISTS `fee_packet` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `title` varchar(50) NOT NULL COMMENT '套餐标题',
  `price` int(10) unsigned NOT NULL COMMENT '套餐价格，单位：分',
  `type` smallint(5) unsigned NOT NULL COMMENT '套餐类型：1-基础服务，2-高级服务，3-钻石服务，4-上帝服务',
  `detail` varchar(2000) NOT NULL COMMENT '套餐描述信息，html格式',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `create_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '记录创建者id',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  `update_id` bigint(20) unsigned DEFAULT NULL COMMENT '记录更新者id',
  PRIMARY KEY (`id`)
) COMMENT='费率套餐表';

CREATE TABLE IF NOT EXISTS `order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `order_id` varchar(30) NOT NULL COMMENT '内部订单编号',
  `customer_name` varchar(50) NOT NULL COMMENT '客户姓名',
  `customer_phone_no` varchar(11) NOT NULL COMMENT '客户手机号码',
  `appointment_time` datetime DEFAULT NULL COMMENT '期望的上门时间',
  `customer_address` varchar(100) DEFAULT NULL COMMENT '地址',
  `pet_type` varchar(10) DEFAULT NULL COMMENT '宠物类型，如：猫、狗',
  `pet_height` int(10) unsigned DEFAULT NULL COMMENT '宠物身高，单位：cm',
  `pet_length` int(10) unsigned DEFAULT NULL COMMENT '宠物体长，单位：cm',
  `pet_dead_time` datetime DEFAULT NULL COMMENT '宠物死亡时间',
  `pet_dead_reason` varchar(200) DEFAULT NULL COMMENT '宠物死亡原因',
  `introducer` bigint(20) unsigned DEFAULT NULL COMMENT '推荐人,即下单人的推荐人，对应member表中的introducer',
  `introducer_channel` varchar(50) DEFAULT NULL COMMENT '推荐人渠道',
  `introducer_take_status` smallint(5) unsigned DEFAULT '1' COMMENT '推荐人提款状态：1-未提款，2-提款中，3-已提款',
  `introducer_take_money` int(10) unsigned DEFAULT NULL COMMENT '推荐人可提款金额，单位：分',
  `fee_packet_id` bigint(20) unsigned NOT NULL COMMENT '套餐id',
  `fee_packet_title` varchar(50) NOT NULL COMMENT '套餐标题',
  `total_pay_fee` int(10) unsigned NOT NULL COMMENT '套餐金额，单位：分',
  `pre_pay_fee` int(10) unsigned NOT NULL COMMENT '定金，单位：分',
  `pre_order_id` varchar(32) NOT NULL COMMENT '定金内部订单编号',
  `pre_out_order_id` varchar(64) DEFAULT NULL COMMENT '定金外部订单编号',
  `rest_pay_fee` int(10) unsigned NOT NULL COMMENT '尾款，单位：分',
  `rest_order_id` varchar(32) NOT NULL COMMENT '尾款内部订单编号',
  `rest_out_order_id` varchar(64) DEFAULT NULL COMMENT '尾款外部订单编号',
  `status` smallint(5) unsigned NOT NULL DEFAULT '1' COMMENT '订单状态：1.待支付 2.待出发 3.待服务 4.待火化 5.待制品 6待发货 7.已发货 8.已完成',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `create_id` bigint(20) unsigned NOT NULL COMMENT '创建者id，即下单人member主键id',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  `update_id` bigint(20) unsigned DEFAULT NULL COMMENT '更新者id',
  PRIMARY KEY (`id`),
  KEY `ck_create_id` (`create_id`,`create_time`) USING BTREE
) COMMENT='订单表';